const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')}));
$('#theme')?.addEventListener('click',()=>document.body.classList.toggle('dark'));
const flows={start:['Verify battery state and cranking speed','Confirm ignition spark at a plug','Confirm fuel pump operation','Measure fuel pressure with correct equipment/specification','Verify injector pulse / D-Jet triggering','Inspect vacuum/intake integrity','Check compression/mechanical timing if spark and fuel are present'],idle:['Confirm symptom cold vs warm','Inspect vacuum hoses and intake leaks','Inspect throttle/idle-air path','Verify ignition condition and advance operation','Verify D-Jet fuel delivery and sensor connections','Check cylinder contribution / compression'],shift:['Confirm Park/Neutral idle behavior','Verify transmission fluid condition/level by correct procedure','Check engine idle quality before transmission diagnosis','Inspect vacuum and ignition','Observe RPM drop when gear engages','Inspect mounts/linkage if vibration is primary symptom'],misfire:['Identify affected cylinder(s)','Inspect plug, lead, cap and rotor','Swap/test components methodically','Verify injector operation','Check vacuum leak near affected runner','Compression/leak-down if ignition/fuel checks pass'],spark:['Battery/grounds','Coil supply','Coil output','Points/triggering and distributor','Cap and rotor','Individual leads/plugs'],fuel:['Listen/verify pump operation','Inspect fuse/relay/power path','Check tank-to-pump supply and filter','Measure regulated pressure using verified specification','Verify injector pulse','Inspect cold-start and D-Jet control inputs'],rich:['Inspect plugs/exhaust symptoms','Check intake/vacuum integrity','Verify fuel pressure against exact specification','Inspect D-Jet sensor wiring/inputs','Check injector leakage and cold-start valve','Do not adjust mixture until faults are excluded'],hot:['Separate no-crank from crank/no-start','Check spark while fault is present','Check fuel pressure retention/delivery','Inspect temperature-related electrical connections','Check injector triggering','Compare cold vs hot measurements']};
$$('.symptom').forEach(b=>b.addEventListener('click',()=>{$('#result').innerHTML='<ol>'+flows[b.dataset.result].map(x=>'<li>'+x+'</li>').join('')+'</ol>'}));
const systemTests={'Engine / D-Jetronic':['Battery/cranking baseline','Spark quality','Fuel delivery/pressure','Injector triggering','Vacuum/intake integrity','D-Jet sensor inputs','Compression/mechanical condition'],'Ignition':['Battery voltage/grounds','Coil supply and output','Distributor triggering','Cap/rotor inspection','Lead resistance/condition','Plug condition','Advance operation'],'Fuel delivery':['Pump electrical supply','Tank outlet/supply','Filter restriction','Pressure/regulation','Injector pulse','Injector leakage'],'Cooling':['Coolant level/leaks','Belts/hoses','Thermostat flow','Radiator airflow','Fan operation','Temperature verification'],'Charging / starting':['Battery state','Terminal/ground voltage drop','Starter control signal','Starter draw/operation','Alternator output','Regulator/wiring'],'Transmission':['Fluid/leaks','Linkage','Engine idle/load interaction','Engagement behavior','Shift behavior','Driveline/mounts'],'Brakes':['Fluid/leaks','Pedal feel','Booster/vacuum','Pads/rotors','Calipers/hoses','Parking brake'],'Steering / suspension':['Tire/wheel baseline','Play inspection','Ball joints/bushings','Tie rods/steering linkage','Shocks/springs','Wheel bearings/alignment'],'Lighting / electrical':['Battery/grounds','Fuse integrity','Power at load','Switch/control path','Connector voltage drop','Ground at load'],'HVAC':['Blower/fuse','Controls','Vacuum controls','Heater valve/coolant flow','A/C electrical command','Refrigerant diagnosis by qualified procedure'],'Body / water leaks':['Identify entry point','Inspect seals/drains','Trace water path upward','Inspect corrosion','Dry/repair source','Re-test with controlled water']};
$('#buildPath')?.addEventListener('click',()=>{const s=$('#system').value, y=$('#symptom').value, tests=systemTests[s]||[];$('#path').innerHTML='<b>'+s+' — '+y+'</b><p>Run in order; record each result before moving on.</p><ol>'+tests.map((x,i)=>'<li><b>Step '+(i+1)+':</b> '+x+'</li>').join('')+'</ol>'});
let tests=[];$('#recordTest')?.addEventListener('click',()=>{let n=$('#testName').value.trim(),v=$('#testValue').value.trim();if(!n||!v)return;tests.unshift({n,v,t:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});tests=tests.slice(0,20);$('#testHistory').innerHTML=tests.map(x=>'<div><b>'+x.n+'</b>: '+x.v+' <span class="muted">'+x.t+'</span></div>').join('');$('#testName').value='';$('#testValue').value=''});
const nodeInfo={'Battery':'Inspect terminals, grounds, state of charge and voltage drop under load.','Ignition switch':'Trace battery feed, switched output and starter/run circuits.','Starter':'Verify control signal, cable voltage drop, grounds and starter operation.','Alternator':'Check belt, wiring, ground and charging output with verified procedure.','Coil':'Verify primary supply/triggering and secondary output before condemning the coil.','Distributor':'Inspect points/triggering, cap, rotor, advance mechanism and connections.','Spark plugs':'Read plug condition and verify spark/cylinder contribution.','D-Jet ECU':'Verify power, grounds, connectors and sensor/trigger inputs before ECU replacement.','Injectors':'Verify pulse, electrical connection and fuel delivery/leakage.','Fuel pump':'Verify power/ground, supply from tank, filter and regulated pressure.','Sensors / trigger points':'Inspect connectors and verify individual inputs using exact component specifications.','Lighting / fuse circuits':'Trace source → fuse → switch/control → load → ground.'};
$$('.wire-toolbar button').forEach(b=>b.addEventListener('click',()=>{let c=b.dataset.circuit;$$('.wire').forEach(w=>w.classList.toggle('selected',c==='all'||w.classList.contains(c)));$('#wireInfo').innerHTML='<b>'+b.textContent+' circuit selected.</b> Follow highlighted functional paths, then test source, control, load and ground in sequence.'}));
$$('.node').forEach(n=>n.addEventListener('click',()=>{$$('.node').forEach(x=>x.classList.remove('selected'));n.classList.add('selected');$('#wireInfo').innerHTML='<b>'+n.dataset.node+'</b><br>'+nodeInfo[n.dataset.node]}));
const service=['Battery terminals & grounds','Engine oil / leaks','Coolant / hoses / belts','Fuel hoses & leaks','Ignition leads / cap / rotor','Brake fluid / leaks','Tires / pressures','Transmission leaks / behavior','Lighting / signals','Underbody / rust inspection'];
const sl=$('#serviceList');if(sl){service.forEach((x,i)=>{let l=document.createElement('label');l.className='service-item';l.innerHTML='<input type="checkbox"> <span>'+x+'</span>';sl.appendChild(l)});$('#reset')?.addEventListener('click',()=>sl.querySelectorAll('input').forEach(x=>x.checked=false))}
const note=$('#note');if(note){try{note.value=localStorage.getItem('116-notes')||'';note.addEventListener('input',()=>localStorage.setItem('116-notes',note.value))}catch(e){}}
